##### 2-00. 그룹 나누기
* 모수, 비모수 검정은 대부분 여러 개 그룹에 대해 평균, 중앙값 등이 동일한지 동일하지 않은지를 검정하는 것
* 데이터를 그룹벼로 나누는 일을 할 수 있어야 한다.
* 제공되는 파일의 형태에 따라 그룹을 나누는 방법이 다르므로 연습이 필요하다.
* 다양한 연산을 하면서 index사용은 위험성이 있어 ndarray로 변환하는 사용하는 것이 좋다.
* element-wise 동작은 위험함



**그룹 데이터가 각각의 컬럼으로 구성된 경우**
* 그룹은 컬럼명을 사용해 분리한다.
* 다음은 20대와 40대의 수면시간에 대한 20명 데이터이다.

In [1]:
# [1] 데이터 확인
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/Soyoung-Yoon/data_02/main/sleepage.csv"
df = pd.read_csv(url)
print(df.head(3))

   stime20s  stime40s  ID
0         4         5   1
1         4         5   2
2         5         6   3


In [3]:
# [2] 그룹을 나누어 ndarray로 변경해 저장하기
# 20대와 40대 수면시간을 각각 gA, gB로 저장
gA = df['stime20s'].to_numpy()
gB = df['stime40s'].to_numpy()
print(gA, gB, sep="\n")

[4 4 5 5 6 6 7 3 8 7 8 8 7 7 7 6 8 5 6 6]
[5 5 6 7 6 7 7 5 5 6 8 7 6 6 8 7 7 6 5 8]


**그룹 데이터가 그룹정보, 값정보 컬럼으로 구성된 경우**
* 그룹정보 컬럼을 사용해 indexing으로 값 정보 컬럼을 나눈다.
* 다음은 iris데이터로, 각 50개씩의 3개의 품종에 대한 데이터가 있다.


In [4]:
# [1] 데이터 확인하기
import pandas as pd
import seaborn as sns
iris = sns.load_dataset('iris')
print(iris.head(3))

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa


In [5]:
# [2] 품종의 종룍 확인
print(iris['species'].unique())

['setosa' 'versicolor' 'virginica']


In [6]:
# [3] 품종별 그룹을 나누어 ndarray로 변경해 저장하기(indexing 사용)
# target = 'sepal_length'로 한다.
target='sepal_length'
gA = iris.loc[iris['species']=='setosa', target].to_numpy()
gB = iris.loc[iris['species']=='versicolor', target].to_numpy()
gC = iris.loc[iris['species']=='virginica', target].to_numpy()

# [4] 품종별 그룹을 나누어 ndarray로 변경해 저장하기(groupby 사용)
# tar_get='sepal_length'
gA, gB, gC = [s.to_numpy() for _, s in iris.groupby('species')['sepal_length']]
print(gA, gB, gC, sep="\n")

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5. ]
[7.  6.4 6.9 5.5 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8
 6.2 5.6 5.9 6.1 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.
 6.7 6.3 5.6 5.5 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7]
[6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7
 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7
 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8 6.7 6.7 6.3 6.5 6.2 5.9]


#### 2-01. 정규성 검정
* Shapiro-Wilk Test, Kolmogorov-Smirnov Test, D'Agostino Pearson Test, Anderson Darling Test
* 귀무가설- 데이터셋이 정규분포를 따른다.
* 대립가설- 데이터셋이 정규분포를 따르지 않는다.
* 유의수준 0.05인 경우, pvalue > 0.05, 정규성이 보장된다고 할 수 있다.
* 검정통계량 < 임계값, 정규성이 보장된다고 할 수 있다.

In [8]:
# [1] dir 사용하여 함수이름 찾기
import pandas as pd
import scipy.stats
s = pd.Series(dir(scipy.stats))
cond = s.str.startswith('sh')
print(s[cond])

308    shapiro
dtype: object


In [9]:
cond = s.str.startswith('k')
print(s[cond])

197          kappa3
198          kappa4
199             kde
200      kendalltau
201         kruskal
202        ks_1samp
203        ks_2samp
204           ksone
205           kstat
206        kstatvar
207          kstest
208           kstwo
209       kstwobign
210        kurtosis
211    kurtosistest
dtype: object


In [10]:
#[2] 20대와 40대의 수면시간 데이터 불러오기
url = "https://raw.githubusercontent.com/Soyoung-Yoon/data_02/main/sleepage.csv"
df = pd.read_csv(url)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   stime20s  20 non-null     int64
 1   stime40s  20 non-null     int64
 2   ID        20 non-null     int64
dtypes: int64(3)
memory usage: 608.0 bytes
None


In [11]:
#[3] 20대와 40대 그룹의 수면시간을 나누어 저장(numpy로 저장)
gA = df['stime20s'].to_numpy()
gB = df['stime40s'].to_numpy()
print(gA, gB, sep="\n")

[4 4 5 5 6 6 7 3 8 7 8 8 7 7 7 6 8 5 6 6]
[5 5 6 7 6 7 7 5 5 6 8 7 6 6 8 7 7 6 5 8]


In [ ]:
# [4] 1. shapiro wilks test: 데이터가 정규분포인지 아닌지를 검정
from scipy.stats import shapiro
A_statistic, A_pvalue = shapiro(gA)
B_statistic, B_pvalue = shapiro(gB)
print(f"A 검정통계량: {A_statistic:.4f}, A pvalue: {A_pvalue:.4f}")
print(f"B 검정통계량: {B_statistic:.4f}, B pvalue: {B_pvalue:.4f}")
print("기각" if A_pvalue <= 0.05 else "채택")
print("기각" if B_pvalue <= 0.05 else "채택")

A 검정통계량: 0.9239, A pvalue: 0.1180
B 검정통계량: 0.8810, B pvalue: 0.0184
채택
기각


In [16]:
# [4] 2. ks-test: 두 개의 데이터가 같은 분포인지 아닌지 검정
# norm은 정규분포를 의미하며, pvalue > 0.05인 경우 귀무가설을 채택
from scipy.stats import kstest
A_statistic, A_pvalue = kstest(gA, "norm")
B_statistic, B_pvalue = kstest(gB, "norm")
print(f"A 검정통계량: {A_statistic:.4f}, A pvalue: {A_pvalue:.4f}")
print(f"B 검정통계량: {B_statistic:.4f}, B pvalue: {B_pvalue:.4f}")
print("채택" if A_pvalue > 0.05 else "기각")
print("기각" if A_pvalue <= 0.05 else "채택")
print("채택" if B_pvalue > 0.05 else "기각")

A 검정통계량: 0.9987, A pvalue: 0.0000
B 검정통계량: 1.0000, B pvalue: 0.0000
기각
기각
기각


In [17]:
# [4] 3. D'Agostino-Pearson: 8개 이상의 데이터가 필요, 50개 미만일 때 정확도가 떨어짐
# normaltest(data): 데이터가 정규분포인지 아닌지 검정, pvalue > 0.05인 경우 귀무가설을 채택
from scipy.stats import normaltest
A_statistic, A_pvalue = normaltest(gA)
B_statistic, B_pvalue = normaltest(gB)
print(f"A 검정통계량: {A_statistic:.4f}, A pvalue: {A_pvalue:.4f}")
print(f"B 검정통계량: {B_statistic:.4f}, B pvalue: {B_pvalue:.4f}")
print("채택" if A_pvalue > 0.05 else "기각")
print("기각" if A_pvalue <= 0.05 else "채택")
print("채택" if B_pvalue > 0.05 else "기각")

A 검정통계량: 1.1732, A pvalue: 0.5562
B 검정통계량: 2.0450, B pvalue: 0.3597
채택
채택
채택


In [20]:
# [4] 4. Anderson Darling Test: 임계값을 사용하여 정규분포인지 아닌지를 검정
# anderson(data): 데이터가 정규분포인지 아닌지 검정, 검정통계량 < 임계값인 경우 귀무가설 채택
from scipy.stats import anderson
A_statistic, A_cv, A_sl = anderson(gA)
B_statistic, B_cv, B_sl = anderson(gB)
print(f"A 검정통계량: {A_statistic:.3f}, 임계값: {A_cv}, 유의수준:{A_sl}")
print(f"B 검정통계량: {B_statistic:.3f}, 임계값: {B_cv}, 유의수준:{B_sl}")
# print("채택" if A_statistic < A_cv else "기각")
# print("채택" if B_statistic < B_cv else "기각")

A 검정통계량: 0.560, 임계값: [0.506 0.577 0.692 0.807 0.96 ], 유의수준:[15.  10.   5.   2.5  1. ]
B 검정통계량: 0.892, 임계값: [0.506 0.577 0.692 0.807 0.96 ], 유의수준:[15.  10.   5.   2.5  1. ]


#### 2-02. 등분산성 검정
* bartlett, levene, flinger
* 여러 개 그룹에 대해서 그룹별 차이를 검정하기 위해서 등분산성을 만족해야 함
* p-value > 0.05인 경우 귀무가설을 채택

In [23]:
# [1] dir로 함수이름 찾기
import pandas as pd
import scipy.stats
s = pd.Series(dir(scipy.stats))
cond1 = s.str.startswith('le')
cond2 = s.str.startswith('ba')
cond3 = s.str.startswith('fl')
print(s[cond1])
print(s[cond2])
print(s[cond3])

215         levene
216           levy
217         levy_l
218    levy_stable
dtype: object
83    barnard_exact
84         bartlett
85        bayes_mvs
dtype: object
155    fligner
dtype: object


In [24]:
#[2] 파일 읽어와서 내용확인
import seaborn as sns
iris = sns.load_dataset('iris')
print(iris.head(3))

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa


In [26]:
#[3] 품종별 그룹을 나누어 ndarray로 변경하여 저장(groupby 사용)
gA, gB, gC = [s.to_numpy() for _, s in iris.groupby('species')['sepal_length']]
print(gA, gB, gC, sep="\n")

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5. ]
[7.  6.4 6.9 5.5 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8
 6.2 5.6 5.9 6.1 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.
 6.7 6.3 5.6 5.5 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7]
[6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7
 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7
 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8 6.7 6.7 6.3 6.5 6.2 5.9]


**bartlett 등분산성 검정**
* 데이터셋의 크기가 서로 다른 2개 이상의 집단 사용가능
* 정규성을 가정하므로 데이터가 정규성을 따르지 않을 경우 결과가 왜곡될 수 있음

In [ ]:
#[4] bartlett 검정
from scipy.stats import bartlett

A_statistic, A_pvalue = shapiro(gA)
B_statistic, B_pvalue = shapiro(gB)
C_statistic, C_pvalue = shapiro(gC)

# 귀무가설 채택 - 정규성 만족
print("채택" if A_pvalue > 0.05 else "기각") # 채택
print("채택" if B_pvalue > 0.05 else "기각") # 채택
print("채택" if C_pvalue > 0.05 else "기각") # 채택

# 등분산성 검정
statistic, pvalue = bartlett(gA, gB, gC)
print(f"검정통계량: {statistic:.3f}, p-value: {pvalue:.3f}")
print("채택" if pvalue < 0.05 else "기각")

채택
채택
채택
검정통계량: 16.006, p-value: 0.000
채택


**levene, fliger**
* 정규성을 충족하지 않는 비모수 데이터에 대해서도 사용가능(중앙을 median으로 설정)


In [31]:
#[5] levene 검정, center='mean'으로 지정
from scipy.stats import levene
statistic, pvalue = levene(gA, gB, gC, center='mean')
print(f"statistic: {statistic:.3f}, p-value: {pvalue:.3f}")
print("채택" if pvalue > 0.05 else "기각")

statistic: 7.381, p-value: 0.001
기각


In [33]:
#[5] flinger 검정, center='trimmed', prorportiontocut = 5%로 지정
from scipy.stats import fligner
statistic, pvalue=fligner(gA, gB, gC, center='trimmed', proportiontocut=0.05)
print(f"검정통계량: {statistic:.3f}, p-value: {pvalue:.3f}")
print("채택" if pvalue > 0.05 else "기각")

검정통계량: 13.193, p-value: 0.001
기각
